package com.example.transactionjms.dao;

import com.example.transactionjms.model.AdminMessage;

import java.util.List;

public interface AdminMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_message
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    int insert(AdminMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_message
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    List<AdminMessage> selectAll();
}