package com.example.transactionjms.model;

import java.util.Date;

public class AdminMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_message.id
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_message.ctime
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_message.status
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_message.utime
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    private Date utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_message.content
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_message.message_type
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    private Integer messageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_message.need_open
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    private Boolean needOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_message.title
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_message.id
     *
     * @return the value of admin_message.id
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_message.id
     *
     * @param id the value for admin_message.id
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_message.ctime
     *
     * @return the value of admin_message.ctime
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_message.ctime
     *
     * @param ctime the value for admin_message.ctime
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_message.status
     *
     * @return the value of admin_message.status
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_message.status
     *
     * @param status the value for admin_message.status
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_message.utime
     *
     * @return the value of admin_message.utime
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_message.utime
     *
     * @param utime the value for admin_message.utime
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_message.content
     *
     * @return the value of admin_message.content
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_message.content
     *
     * @param content the value for admin_message.content
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_message.message_type
     *
     * @return the value of admin_message.message_type
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_message.message_type
     *
     * @param messageType the value for admin_message.message_type
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_message.need_open
     *
     * @return the value of admin_message.need_open
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public Boolean getNeedOpen() {
        return needOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_message.need_open
     *
     * @param needOpen the value for admin_message.need_open
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public void setNeedOpen(Boolean needOpen) {
        this.needOpen = needOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_message.title
     *
     * @return the value of admin_message.title
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_message.title
     *
     * @param title the value for admin_message.title
     *
     * @mbg.generated Wed Feb 27 08:44:54 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}